import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import './theme.css';
import { cookies } from 'next/headers';
import { NotificationProvider } from '@/widgets';
import { ModalProvider } from '@/widgets';
import { ThemeSwitcher } from '@/widgets';
import { UserProvider } from '@/features/model/userStore';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get('theme')?.value || '';
  return (
    <html lang="en" className={theme === 'dark' ? 'dark' : ''}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <NotificationProvider>
            <ModalProvider>
              <div className="absolute top-4 right-4 z-3">
                <ThemeSwitcher />
              </div>
              {children}
            </ModalProvider>
          </NotificationProvider>
        </UserProvider>
      </body>
    </html>
  );
}
